spring.config.import=optional:file:.env[.properties]
spring.application.name=barbearia
spring.datasource.url=${PSQL_URL}
spring.datasource.username=${PSQL_USER}
spring.datasource.password=${PSQL_PASS}

spring.jpa.database=projeto_barbearia
spring.jpa.show-sql=true
